create extension if not exists "pgcrypto";

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text unique,
  first_name text not null default '',
  last_name text not null default '',
  age integer not null default 0,
  height_cm integer not null default 0,
  weight_kg numeric(6, 2) not null default 0,
  goal text not null default 'Definición',
  activity_level text not null default 'Actividad moderada',
  training_level text not null default 'Intermedio',
  member_since text not null default '',
  active_routine_id bigint null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.routines (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references public.profiles(id) on delete cascade,
  name text not null,
  days_per_week integer not null default 4,
  color text not null default '#12EFD3',
  categories jsonb not null default '[]'::jsonb,
  description text null,
  tags text[] null,
  avg_minutes integer null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.routine_days (
  id bigint generated by default as identity primary key,
  routine_id bigint not null references public.routines(id) on delete cascade,
  position integer not null,
  name text not null,
  focus text not null default '',
  description text null,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.routine_day_exercises (
  id bigint generated by default as identity primary key,
  routine_day_id bigint not null references public.routine_days(id) on delete cascade,
  position integer not null,
  name text not null,
  muscle text not null,
  implement text null,
  secondary_muscles text[] null,
  notes text null,
  sets_json jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.workout_sessions (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references public.profiles(id) on delete cascade,
  routine_id bigint null references public.routines(id) on delete set null,
  session_date date not null,
  day_name text not null,
  muscle_summary text not null default '',
  session_focus text null,
  duration_seconds integer not null default 0,
  kcal integer not null default 0,
  volume numeric(10, 2) not null default 0,
  avg_rpe numeric(4, 2) not null default 0,
  notes text null,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.workout_session_exercises (
  id bigint generated by default as identity primary key,
  workout_session_id bigint not null references public.workout_sessions(id) on delete cascade,
  position integer not null,
  name text not null,
  muscle text not null,
  implement text null,
  secondary_muscles text[] null,
  max_kg numeric(10, 2) not null default 0,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.workout_session_sets (
  id bigint generated by default as identity primary key,
  workout_session_exercise_id bigint not null references public.workout_session_exercises(id) on delete cascade,
  position integer not null,
  kg numeric(10, 2) not null default 0,
  reps integer not null default 0,
  rpe numeric(4, 2) null,
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.profiles
  add constraint profiles_active_routine_id_fkey
  foreign key (active_routine_id) references public.routines(id) on delete set null;

create index if not exists routines_owner_id_idx on public.routines(owner_id);
create index if not exists routine_days_routine_id_idx on public.routine_days(routine_id, position);
create index if not exists routine_day_exercises_day_id_idx on public.routine_day_exercises(routine_day_id, position);
create index if not exists workout_sessions_owner_id_idx on public.workout_sessions(owner_id, session_date desc);
create index if not exists workout_session_exercises_session_id_idx on public.workout_session_exercises(workout_session_id, position);
create index if not exists workout_session_sets_exercise_id_idx on public.workout_session_sets(workout_session_exercise_id, position);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists set_profiles_updated_at on public.profiles;
create trigger set_profiles_updated_at
before update on public.profiles
for each row
execute function public.set_updated_at();

drop trigger if exists set_routines_updated_at on public.routines;
create trigger set_routines_updated_at
before update on public.routines
for each row
execute function public.set_updated_at();

alter table public.profiles enable row level security;
alter table public.routines enable row level security;
alter table public.routine_days enable row level security;
alter table public.routine_day_exercises enable row level security;
alter table public.workout_sessions enable row level security;
alter table public.workout_session_exercises enable row level security;
alter table public.workout_session_sets enable row level security;

create policy "profiles_select_own" on public.profiles
for select to authenticated
using ((select auth.uid()) = id);

create policy "profiles_insert_own" on public.profiles
for insert to authenticated
with check ((select auth.uid()) = id);

create policy "profiles_update_own" on public.profiles
for update to authenticated
using ((select auth.uid()) = id)
with check ((select auth.uid()) = id);

create policy "routines_manage_own" on public.routines
for all to authenticated
using ((select auth.uid()) = owner_id)
with check ((select auth.uid()) = owner_id);

create policy "routine_days_manage_own" on public.routine_days
for all to authenticated
using (
  exists (
    select 1
    from public.routines
    where public.routines.id = routine_id
      and public.routines.owner_id = (select auth.uid())
  )
)
with check (
  exists (
    select 1
    from public.routines
    where public.routines.id = routine_id
      and public.routines.owner_id = (select auth.uid())
  )
);

create policy "routine_day_exercises_manage_own" on public.routine_day_exercises
for all to authenticated
using (
  exists (
    select 1
    from public.routine_days
    join public.routines on public.routines.id = public.routine_days.routine_id
    where public.routine_days.id = routine_day_id
      and public.routines.owner_id = (select auth.uid())
  )
)
with check (
  exists (
    select 1
    from public.routine_days
    join public.routines on public.routines.id = public.routine_days.routine_id
    where public.routine_days.id = routine_day_id
      and public.routines.owner_id = (select auth.uid())
  )
);

create policy "workout_sessions_manage_own" on public.workout_sessions
for all to authenticated
using ((select auth.uid()) = owner_id)
with check ((select auth.uid()) = owner_id);

create policy "workout_session_exercises_manage_own" on public.workout_session_exercises
for all to authenticated
using (
  exists (
    select 1
    from public.workout_sessions
    where public.workout_sessions.id = workout_session_id
      and public.workout_sessions.owner_id = (select auth.uid())
  )
)
with check (
  exists (
    select 1
    from public.workout_sessions
    where public.workout_sessions.id = workout_session_id
      and public.workout_sessions.owner_id = (select auth.uid())
  )
);

create policy "workout_session_sets_manage_own" on public.workout_session_sets
for all to authenticated
using (
  exists (
    select 1
    from public.workout_session_exercises
    join public.workout_sessions on public.workout_sessions.id = public.workout_session_exercises.workout_session_id
    where public.workout_session_exercises.id = workout_session_exercise_id
      and public.workout_sessions.owner_id = (select auth.uid())
  )
)
with check (
  exists (
    select 1
    from public.workout_session_exercises
    join public.workout_sessions on public.workout_sessions.id = public.workout_session_exercises.workout_session_id
    where public.workout_session_exercises.id = workout_session_exercise_id
      and public.workout_sessions.owner_id = (select auth.uid())
  )
);
